### PR TITLE
Implemented the retrieve unit_of_measure methods.

### LINKED ISSUE #71: Create API endpoints for retrieving unit of measures.
Definition of done:

Here, I will create API endpoints that will allow me to retrieve unit of measures from the database. Additionally, I will write unit tests to ensure the functionality of the endpoint.

### PR DESCRIPTION
**Pull request by MousamiKhadilkar**
Implemented the retrieve unit_of_measure methods.

### CODE REVIEW

**Review by VidhiS07 — APPROVED** [review]
Could you please add contracts-related statements and push changes ? Please do not use short names in functions like uom; instead, give them actual long names like get_unit_of_measure(). Apart from that, all unit tests have been executed, and the code appears to have been nicely written.

**Review by aanuhya31 — APPROVED** [review]
Overall, the code implementation looks after modifying with the suggested changes. The added test case also ensure the functionality of the code. I approve the changes.

**Review by VidhiS07 — COMMENTED** [review]
Columns names are different in Unit_of_measures Table. The correct table columns are unit_of_measure_id & unit_of_measure_name. Please check database table once and modify the query in unit_of_measure.py file.

**Review by VidhiS07 — APPROVED** [review]
Requested code changes are implemented. Code looks fine to me.

**Pull request merged**
