### PR TITLE
Implemented API endpoints for updating the details of the existing order in the database.

### LINKED ISSUE #73: Create API endpoints for updating the details of existing order in the database.
Definition of done:

- As a developer, I want to implement API endpoint that allows to update the details of existing orders in the grocery store.
- This endpoint will connect to the existing database table and update the information.
- Unit test cases are written to verify the functionality of this API endpoint.

### PR DESCRIPTION
**Pull request by MousamiKhadilkar**
Implemented API endpoints for updating the details of the existing order in the database.

### CODE REVIEW

**Review by VidhiS07 — COMMENTED** [review]
Some statements are not covered in unit test, Please try to cover those.
Also, Change function name from update_order_amount to update_order_details or update_order_information in both file orders.py & test_orders.py and unit test for update order information is missing in test_server.py

Please do above changes and push again.

**Review by aanuhya31 — CHANGES_REQUESTED** [review]
I agree with the suggested changes mentioned above to rename the function update_order_amount and add unit test for update_order_information in test_server.py. Please push again with these changes.

**Review by VidhiS07 — APPROVED** [review]
Changes are fine. Functions are given more appropriate names. unit tests are run, and there is sufficient coverage. You're good to go.

**Review by aanuhya31 — APPROVED** [review]
All the required changes have been made successfully. With these changes in place, I believe you are ready to merge.

**Pull request merged**
